### PR TITLE
Homepage 2

### PR DESCRIPTION
**Pull request by monicakogler**
this is close. need to test on actual mobile device, and was just thinking about the bullets in the blue section with @psugihara. considering making "serverless self-hosting" its own section...

### CODE REVIEW

**Comment by alexfarrill** [comment]
Looks good, two questions:
- Should we start with the hero image visible?  I think seeing the product right away gives a lot of information
- I think we should swap the order of the social proof with the product details below it, I want some more product details before looking for social validation.  wdyt?

**Comment by monicakogler** [comment]
@alexfarrill cool i made the hero image visible on load. makes sense about testimonials, will update with the other change.

**Review by psugihara — APPROVED** [review]
think this is feeling goood :)

**Comment by monicakogler** [comment]
@psugihara will u sanity check me on dark mode please?

**Review by psugihara — APPROVED** [review]
look great to me

**Pull request merged**
