### PR TITLE
Welcome template

### PR DESCRIPTION
**Pull request by elliothursh**
## Describe your changes
Adds new Welcome template.

image

## Issue link
N/A

## Checklist before requesting a review

- [X] I have performed a self-review of my code
- [X] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by elliothursh** [comment]
@monicakogler can you give this a pass when you have a minute? https://mailing-dynamic-demo-git-welcome-template-sofn.vercel.app/previews/Welcome/preview

**Review by psugihara — APPROVED** [review]
lgtm

**Comment by monicakogler** [comment]
cool looks good, just a few little things please:

- [ ] idk if it's just me but the the font weight in the logo looks light, could we use this one?
 

- [ ] bold "The open source platform..." in header
- [ ] capitalize D in "Check out the Docs" 
- [ ] will the newsletter show up in this list too? i think it probably should? and in that case could we match how the bg works there? like the email body bg is our black (111) and then the background of the page is true black (000)? 

ty 🙏🙏🙏

**Comment by elliothursh** [comment]
The Newsletter won't show up by default in these emails, I can copy it over if we want though. I will match the backgrounds for now.

**Review by monicakogler — APPROVED** [review]

**Pull request merged**
