### PR TITLE
mailing.run/white-glove

### PR DESCRIPTION
**Pull request by psugihara**
## Describe your changes

Adds /white-glove to `web`

## Checklist before merging

- [x] design qa
- [x] copy qa (does this feel as premium as it is?)
- [x] confirm pricing
- [x] swap to real typeform link

### CODE REVIEW

**Review by alexfarrill — CHANGES_REQUESTED** [review]
It looks great!

- Chrome mobile has a white strip on the side (see screenshot)
- When you first load the page the button animates in, but if you reload the page it doesn't.  It may not be a bug, I just thought it was weird.

**Comment by alexfarrill** [comment]
IMG_22826797D3CD-1

**Comment by alexfarrill** [comment]
I think it is too big by one or two breakpoints, this is full screen on my 16" laptop

image

I'd rather see the whole pricing page fit on this screen

**Comment by psugihara** [comment]
nice, thx for checking it out. I think monica fixed the white bar, I'll take a look at that weird animation thing... it should not animate so something funky is happening.

Also going to delete a pricing row to simplify / shorten.

**Review by alexfarrill — APPROVED** [review]

**Comment by monicakogler** [comment]
looks good but should we change the title so "White Glove" fits or am i nitpicking?

Screen Shot 2022-11-30 at 1 26 13 PM

**Review by monicakogler — APPROVED** [review]

**Comment by alexfarrill** [comment]
haha +1 dont' ship with "Glove by Mailing" plz lol

**Review by alexfarrill — APPROVED** [review]

**Comment by monicakogler** [comment]
haha i think it's just bad luck with how the browser wraps text in the tab... i took a word out and seems to work now

Screen Shot 2022-11-30 at 2 54 46 PM

**Pull request merged**
