### PR TITLE
replace mjml-react with @faire/mjml-react and fix types issues (alex version, clean)

### PR DESCRIPTION
**Pull request by alexfarrill**
adds 2 tweaks to @faire/mjml-react
- add @types/react to cli dependencies
- moves a type definition to inline from custom.d.ts because Link.tsx gets copied into the user's emails dir but custom.d.ts does not

### CODE REVIEW

**Review by psugihara — APPROVED** [review]
nice work, that makes sense.

looks great!

**Comment by m5r** [comment]
Hey, any update about this? It looks like the e2e tests are passing finally :smile:  
Let me know if there is anything else I can do to help get this merged

**Comment by alexfarrill** [comment]
The redwood_ts test is also failing in master and is unrelated to the changes in this branch I believe.  (In both branches it's complaining about the yarn version used to run create-redwood-app)

**Comment by psugihara** [comment]
We've been running this in prod on iterate.world for a week. Seems good 👍, let's merge monday.

**Comment by alexfarrill** [comment]
@m5r this has been release in Mailing 1.0.0.  Thanks again for the great work here 🥇 !

**Comment by m5r** [comment]
@alexfarrill thanks a lot for taking the time to push this one through :heart:

**Pull request merged**
